openapi: 3.0.0
info:
  title: Email API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /email/get-all-mail:
    get:
      summary: Get all emails
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Returns list of all mails
  /email/send-mail:
    post:
      summary: Send an email
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                body:
                  type: string
              required:
                - subject
                - body
      responses:
        "200":
          description: Returns created mail object
  /email/read-mail:
    post:
      summary: Mark an email as read
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
                - id
      responses:
        "200":
          description: SReturns message and altered mail object
  /email/get-mail/{id}:
    get:
      summary: Get an email by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Returns mail object of id
  /user/login:
    post:
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Returns refresh and access token
  /user/refresh_token:
    get:
      summary: Refresh access token
      responses:
        "200":
          description: Returns refreh token and new access token
    delete:
      summary: Clear refresh token
      responses:
        "200":
          description: Message==> Refresh Token Successfully cleared
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
